[tools]
"aqua:anthropics/claude-code" = "latest"
"aqua:cli/cli" = "2.87.3"
"aqua:marp-team/marp-cli" = "4.5.0"
"github:k1LoW/mo" = "v0.23.2"
"github:sago35/tinygo-autocmpl" = "v0.8.0"
"github:sivchari/gopls-lazy" = "v0.3.0"
node = "latest"
"npm:ccusage" = "latest"
"npm:textlint" = "15.8.0"
"npm:textlint-rule-prh" = "6.1.0"
"npm:textlint-rule-preset-ja-technical-writing" = "12.0.2"

[settings]
idiomatic_version_file_enable_tools = ["node"]

[env]
DISABLE_AUTOUPDATER = "1"

[tool_alias]
terraform = "tf"
